fix: Update FAQ
matter-labs/zksync-docs pull request #147
Opened 2024-06-26 23:41 UTC by bxpana

# Description

Added message regarding issues with accessing ZKsync Lite and Era frontends

## Linked Issues

## Additional context

2024-06-27 08:41 UTC, JackHamer09 submitted a review, later dismissed

2024-07-02 21:43 UTC, itsacoyote requested changes

2024-07-02 21:43 UTC, itsacoyote commented on content/00.build/95.resources/60.faq.md
> +Please see our Privacy Policy [link](https://zksync.io/privacy) and
```suggestion
Please see our [Privacy Policy](https://zksync.io/privacy) and
```

2024-07-02 21:43 UTC, itsacoyote commented on content/00.build/95.resources/60.faq.md
> +Terms of Service [link](https://zksync.io/terms) for the most up-to-date relevant information.
```suggestion
[Terms of Service](https://zksync.io/terms) for the most up-to-date relevant information.
```

2024-07-02 21:43 UTC, itsacoyote commented on content/00.build/95.resources/60.faq.md
> +## Why can't I use [ZKsync Portal](https://portal.zksync.io/bridge) or [ZKsync Lite](https://lite.zksync.io/)?
Links do not work inside of headers, so we should remove them. 
```suggestion
## Why can't I use ZKsync Portal or ZKsync Lite?
```

2024-07-03 17:47 UTC, itsacoyote approved these changes

2024-07-03 17:47 UTC, merged