fix: update broken links
matter-labs/zksync-docs pull request #265
Opened 2024-11-21 08:27 UTC by MexicanAce

# Description

Links are broken for the `era-compiler-solidity` repo, as it looks like that repo was refactored

2024-11-21 08:45 UTC, hedgar2017 requested changes
Honestly, I don't think these docs and especially source code links are useful to anyone.

They shall be superseded by [zksolc CLI docs](https://github.com/matter-labs/era-compiler-solidity/blob/main/docs/src/02-command-line-interface.md) where we'll be able to keep them up-to-date.

2024-11-21 08:45 UTC, hedgar2017 commented on content/10.zk-stack/10.components/70.compiler/20.specification/70.binary-layout.md
> +- [Definition of metadata hash.](https://github.com/matter-labs/era-compiler-solidity/blob/main/era-compiler-solidity/src/project/contract/metadata.rs)
This is the definition of metadata hash *preimage*, not the hash itself.

2024-11-21 08:45 UTC, hedgar2017 commented on content/10.zk-stack/10.components/70.compiler/20.specification/70.binary-layout.md
> +- [Front-end code that passes hash to the assembly.](https://github.com/matter-labs/era-compiler-solidity/blob/main/era-compiler-solidity/src/project/contract/mod.rs#L106)
Not to the *assembly*, but simply further down the compilation pipeline.

2024-11-21 08:48 UTC, hedgar2017 commented
@MexicanAce let me describe it properly in zksolc docs, and I'll provide a link to be inserted here shortly.

2024-11-21 11:07 UTC, MexicanAce commented
Copy. @hedgar2017 perhaps you wouldn't mind also reviewing this GitHub Discussion which lead me to these broken links: https://github.com/zkSync-Community-Hub/zksync-developers/discussions/784

Someone is trying to regenerate the hash at the end of `zksolc` bytecode from the metadata

2024-11-21 11:20 UTC, hedgar2017 commented
> Copy. @hedgar2017 perhaps you wouldn't mind also reviewing this GitHub Discussion which lead me to these broken links: https://github.com/zkSync-Community-Hub/zksync-developers/discussions/784
> 
> 
> 
> Someone is trying to regenerate the hash at the end of `zksolc` bytecode from the metadata

Sure, will do.

2024-11-22 04:43 UTC, hedgar2017 commented
@MexicanAce done!
Please use [this](https://github.com/matter-labs/era-compiler-solidity/blob/main/docs/src/02-command-line-interface.md#--metadata) and [this](https://github.com/matter-labs/era-compiler-solidity/blob/main/docs/src/02-command-line-interface.md#--metadata-hash) link instead.

2024-11-22 16:18 UTC, MexicanAce commented on content/10.zk-stack/10.components/70.compiler/20.specification/70.binary-layout.md
> +- [Definition of metadata hash.](https://github.com/matter-labs/era-compiler-solidity/blob/main/era-compiler-solidity/src/project/contract/metadata.rs)
```suggestion
- [Definition of metadata hash.](https://github.com/matter-labs/era-compiler-solidity/blob/main/docs/src/02-command-line-interface.md#--metadata)
```

2024-11-22 16:19 UTC, MexicanAce commented on content/10.zk-stack/10.components/70.compiler/20.specification/70.binary-layout.md
> +- [Front-end code that passes hash to the assembly.](https://github.com/matter-labs/era-compiler-solidity/blob/main/era-compiler-solidity/src/project/contract/mod.rs#L106)
```suggestion
- [Front-end code that passes hash to the assembly.](https://github.com/matter-labs/era-compiler-solidity/blob/main/docs/src/02-command-line-interface.md#--metadata-hash)
```

2024-11-22 16:20 UTC, MexicanAce commented
@hedgar2017 Links have been updated, please review the changes

2024-11-22 16:28 UTC, uF4No approved these changes, later dismissed

2024-11-22 16:32 UTC, hedgar2017 commented
@MexicanAce made one more tweak! LGTM now.

2024-11-22 16:32 UTC, hedgar2017 approved these changes

2024-11-22 16:33 UTC, merged